# Generated by Django 6.0.4 on 2026-04-24 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term_number', models.PositiveSmallIntegerField(help_text='e.g., 1 for Term 1', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2026, unique=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.term')),
                ('current_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.year')),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'unique_together': {('current_year', 'current_term')},
            },
        ),
    ]
