# Generated by Django 6.0.4 on 2026-04-24 10:50

from django.db import migrations, models
from django.utils.text import slugify


def populate_academic_sessions_slug(apps, schema_editor):
    AcademicSession = apps.get_model('core', 'AcademicSession')

    academic_sessions = AcademicSession.objects.filter(slug='')

    if academic_sessions.exists():
        for academic_session in academic_sessions:
            academic_session.slug = slugify(f"{academic_session.current_year}-{academic_session.current_term}"[:255])
        AcademicSession.objects.bulk_update(academic_sessions, ['slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_alter_academicsession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.RunPython(populate_academic_sessions_slug),
    ]
