# Generated by Django 6.0.4 on 2026-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_academicsession_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
