# Generated by Django 6.0.3 on 2026-04-05 10:08

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Optional phone number provided by the sender.', max_length=128, null=True, region=None),
        ),
    ]
