# Generated by Django 6.0.3 on 2026-04-07 17:24

import django.db.models.functions.text
import validators.presets
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_contactmessage_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('featured_image', models.ImageField(null=True, upload_to='partners/featured_images/', validators=[validators.presets.validate_image_file])),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_partner_name', violation_error_message='Partner with this name already exists'), models.UniqueConstraint(condition=models.Q(('link__isnull', False)), fields=('link',), name='unique_partner_url', violation_error_message='Partner with this url already exists')],
            },
        ),
    ]
