# Generated by Django 6.0.3 on 2026-04-07 17:56

import resources.validators
import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0004_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='featured_image',
            field=models.ImageField(null=True, storage=seo.models.PublicFilesStorageCallable(),
                                    validators=[resources.validators.validate_image_file_magic]),
        ),
    ]
