# Generated by Django 6.0.3 on 2026-04-08 09:14

import validators.presets
import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_partner_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (160 chars max). Leave blank to auto-generate.', max_length=160),
        ),
        migrations.AddField(
            model_name='partner',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='partner',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (60 chars max). Leave blank to auto-generate.', max_length=60),
        ),
        migrations.AlterField(
            model_name='partner',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for this page', null=True, storage=seo.models.PublicFilesStorageCallable(), upload_to='featured_images/%Y/%m/', validators=[validators.presets.validate_image_file]),
        ),
    ]
