# Generated by Django 6.0.3 on 2026-04-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_partner_meta_description_partner_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='banner_cta',
            field=models.CharField(blank=True, default='Learn More', help_text='Call-to-action button text shown on the banner.', max_length=80),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Partner logo image (displayed on listings and banners).', null=True, upload_to='partners/logos/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='show_as_banner',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this partner as a banner/ad strip on the public website.'),
        ),
    ]
