# Generated by Django 6.0.4 on 2026-04-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_partner_banner_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='focus_keyword',
            field=models.CharField(blank=True, default='', help_text='Enter the main keyword this page should rank for.', max_length=60),
        ),
    ]
