# Generated by Django 6.0.4 on 2026-04-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_emailsubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-created_at']},
        ),
    ]
