# Generated by Django 6.0.4 on 2026-05-01 06:30

import validators.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_partner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Partner logo image (displayed on listings and banners).', null=True, upload_to='partners/logos/', validators=[validators.core.DeepSignatureValidator(allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/tiff', 'image/avif', 'image/heic', 'image/svg+xml', 'image/x-icon'])]),
        ),
    ]
