# Generated by Django 6.0.4 on 2026-05-02 11:12

import validators.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_merge_20260501_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'FAQs',
                'ordering': ['-created_at', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=150)),
                ('author_role', models.CharField(blank=True, default='', max_length=200)),
                ('author_organization', models.CharField(blank=True, default='', max_length=200)),
                ('author_avatar', models.ImageField(blank=True, help_text='Optional profile photo for the author.', null=True, upload_to='testimonials/avatars/', validators=[validators.core.DeepSignatureValidator(allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/tiff', 'image/avif', 'image/heic', 'image/svg+xml', 'image/x-icon'])])),
                ('body', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at', 'order'],
            },
        ),
        migrations.AlterField(
            model_name='customimage',
            name='file',
            field=models.ImageField(storage='public_files', upload_to='wagtail_images/', validators=[validators.core.DeepSignatureValidator(allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/tiff', 'image/avif', 'image/heic', 'image/svg+xml', 'image/x-icon'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='customrendition',
            name='file',
            field=models.ImageField(storage='public_files', upload_to='wagtail_renditions/', validators=[validators.core.DeepSignatureValidator(allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/tiff', 'image/avif', 'image/heic', 'image/svg+xml', 'image/x-icon'])]),
        ),
    ]
