# Generated by Django 6.0.5 on 2026-05-09 10:36

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_faq_testimonial_alter_customimage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=core.fields.SafeHTMLField(blank=True, null=True),
        ),
    ]
