# Generated by Django 6.0.5 on 2026-05-09 22:03

import django.core.files.storage
import validators.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_blogpage_body_alter_blogpage_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdocument',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='wagtail_docs/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='customimage',
            name='file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='wagtail_images/', validators=[validators.core.DeepSignatureValidator(allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/tiff', 'image/avif', 'image/heic', 'image/svg+xml', 'image/x-icon'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='customrendition',
            name='file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='wagtail_renditions/', validators=[validators.core.DeepSignatureValidator(allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/tiff', 'image/avif', 'image/heic', 'image/svg+xml', 'image/x-icon'])]),
        ),
    ]
