# Generated by Django 6.0.5 on 2026-05-09 22:07

import django.core.files.storage
import validators.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_customdocument_file_alter_customimage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='file',
            field=models.ImageField(height_field='height', storage=django.core.files.storage.FileSystemStorage(), upload_to='wagtail_images/', validators=[validators.core.DeepSignatureValidator(allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/tiff', 'image/avif', 'image/heic', 'image/svg+xml', 'image/x-icon'])], verbose_name='file', width_field='width'),
        ),
        migrations.AlterField(
            model_name='customrendition',
            name='file',
            field=models.ImageField(height_field='height', storage=django.core.files.storage.FileSystemStorage(), upload_to='wagtail_renditions/', validators=[validators.core.DeepSignatureValidator(allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/tiff', 'image/avif', 'image/heic', 'image/svg+xml', 'image/x-icon'])], width_field='width'),
        ),
    ]
