# Generated by Django 6.0.5 on 2026-05-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_blogpage_views_blogauthor_blogpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
