# Generated by Django 6.0.5 on 2026-05-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_blogauthor_email_blogauthor_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='whatsapp',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
