# Generated by Django 6.0.5 on 2026-05-13 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_body_to_streamfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', help_text='Not displayed publicly.', max_length=254)),
                ('body', models.TextField(max_length=2000)),
                ('is_approved', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this comment from the public.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.blogpage')),
                ('parent', models.ForeignKey(blank=True, help_text='Set to make this a reply to another comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='website.blogcomment')),
                ('user', models.ForeignKey(blank=True, help_text='Set when the commenter is logged in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
