# Generated by Django 6.0.5 on 2026-05-14 04:27

import validators.core
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_add_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdocument',
            name='file',
            field=models.FileField(storage=website.models.get_public_storage, upload_to='wagtail_docs/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='customimage',
            name='file',
            field=models.ImageField(height_field='height', storage=website.models.get_public_storage, upload_to='wagtail_images/', validators=[validators.core.DeepSignatureValidator(allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/tiff', 'image/avif', 'image/heic', 'image/svg+xml', 'image/x-icon'])], verbose_name='file', width_field='width'),
        ),
        migrations.AlterField(
            model_name='customrendition',
            name='file',
            field=models.ImageField(height_field='height', storage=website.models.get_public_storage, upload_to='wagtail_renditions/', validators=[validators.core.DeepSignatureValidator(allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/tiff', 'image/avif', 'image/heic', 'image/svg+xml', 'image/x-icon'])], width_field='width'),
        ),
    ]
