# Generated by Django 6.0.5 on 2026-05-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_use_storage_callable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
