# Generated by Django 6.0.3 on 2026-04-05 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable menu name (e.g. "Primary Header", "Footer").', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier — auto-populated from the title.', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Page body — supports HTML (wire up TinyMCE in admin).')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Only published pages are visible to the public.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Setting identifier (e.g. "site_name", "support_email").', max_length=50, unique=True)),
                ('value', models.TextField(help_text='The value for this setting.')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Absolute URL, relative path, or named URL pattern.', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the same level (lower = earlier).')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.menu')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent item for nested/dropdown menus.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['menu', 'order', 'title'],
            },
        ),
    ]
