# Generated by Django 6.0.3 on 2026-04-05 06:37

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(help_text='Page body — supports HTML (wire up TinyMCE in admin).'),
        ),
    ]
