# Generated by Django 6.0.4 on 2026-04-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_page_featured_image_page_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(db_index=True, help_text='Setting identifier (e.g. "site_name", "contact_email", "contact_phone", "site_indexing").', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='value',
            field=models.TextField(help_text="The value for this setting. (e.g. 'CBE Resources Hub', 'info@example.com', '+254712345678', 'true')"),
        ),
    ]
