# Generated by Django 6.0.4 on 2026-04-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_sitesetting_key_alter_sitesetting_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='focus_keyword',
            field=models.CharField(blank=True, default='', help_text='Enter the main keyword this page should rank for.', max_length=60),
        ),
    ]
