# Generated by Django 6.0.4 on 2026-04-26 20:58

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_page_focus_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='Human-readable menu name (e.g. "Primary Header", "Footer").', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(db_index=True, help_text='Setting identifier (e.g. "site_name", "contact_email", "contact_phone", "site_indexing").', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_menu_name', violation_error_message='Menu name must be unique'),
        ),
        migrations.AddConstraint(
            model_name='sitesetting',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('key'), name='unique_site_setting_key', violation_error_message='Site Setting key must be unique'),
        ),
    ]
