# Generated by Django 6.0.5 on 2026-05-09 10:36

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_menu_name_alter_sitesetting_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=core.fields.SafeHTMLField(help_text='Page body — supports HTML (wire up TinyMCE in admin).'),
        ),
    ]
