# Generated by Django 6.0.4 on 2026-04-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disable_email_notification',
            field=models.BooleanField(default=False, help_text='If True, the user will not be sent marketing email notifications, however transactional emails will be sent.'),
        ),
    ]
