# Generated by Django 6.0.4 on 2026-04-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_disable_email_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='disable_email_notification',
            field=models.BooleanField(default=False, help_text='If checked, you will not receive marketing emails, however transactional emails will still be sent.'),
        ),
    ]
