# Generated by Django 5.2.8 on 2025-12-01 14:54

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=files.models.file_upload_path)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('file_category', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20)),
                ('size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['file_category', '-created'], name='files_file_file_ca_301ee6_idx'), models.Index(fields=['mime_type'], name='files_file_mime_ty_57dbdc_idx'), models.Index(fields=['-created'], name='files_file_created_eb86db_idx')],
            },
        ),
    ]
