# Generated by Django 5.2.9 on 2026-01-25 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('old_slug', models.SlugField(help_text='Previous slug that should redirect', max_length=255, unique=True)),
                ('new_slug', models.SlugField(help_text='Current slug to redirect to', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='Track redirect usage for analytics')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Slug Redirect',
                'verbose_name_plural': 'Slug Redirects',
                'indexes': [models.Index(fields=['old_slug'], name='seo_slugred_old_slu_cf029f_idx'), models.Index(fields=['content_type', 'object_id'], name='seo_slugred_content_a8b1fe_idx'), models.Index(fields=['-created_at'], name='seo_slugred_created_29003c_idx')],
            },
        ),
    ]
