# Generated by Django 5.2.9 on 2026-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slugredirect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='slugredirect',
            index=models.Index(fields=['new_slug'], name='seo_slugred_new_slu_1be796_idx'),
        ),
    ]
