# Generated by Django 6.0.4 on 2026-04-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_slugredirect_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slugredirect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
