# Generated by Django 6.0.3 on 2026-04-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SIGNUP', 'User Signup'), ('CONTACT', 'Contact Form Submission'), ('RESOURCE_UPLOAD', 'Resource Upload'), ('SECURITY_ALERT', 'Security Alert (Lockout)'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=20)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='recipient email address')),
                ('subject', models.CharField(max_length=255)),
                ('content_html', models.TextField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=15)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx')],
            },
        ),
    ]
