# Generated by Django 6.0.4 on 2026-04-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SIGNUP', 'User Signup'), ('CONTACT', 'Contact Form Submission'), ('RESOURCE_UPLOAD', 'Resource Upload'), ('SECURITY_ALERT', 'Security Alert (Lockout)'), ('GENERAL', 'General'), ('GENERIC_MESSAGE', 'Generic Message')], db_index=True, default='GENERAL', max_length=20),
        ),
    ]
