# Generated by Django 6.0.5 on 2026-05-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SIGNUP', 'User Signup'), ('CONTACT', 'Contact Form Submission'), ('RESOURCE_UPLOAD', 'Resource Upload'), ('SECURITY_ALERT', 'Security Alert (Lockout)'), ('GENERAL', 'General'), ('GENERIC_MESSAGE', 'Generic Message'), ('EMAIL_SUBSCRIPTION', 'Email Subscription'), ('EMAIL_UNSUBSCRIPTION', 'Email Unsubscription')], db_index=True, default='GENERAL', max_length=20),
        ),
    ]
