# Generated by Django 6.0.3 on 2026-04-05 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in selects and navigation.')),
            ],
            options={
                'verbose_name': 'Education Level',
                'verbose_name_plural': 'Education Levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Learning Area',
                'verbose_name_plural': 'Learning Areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='resources.educationlevel')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['level__order', 'order', 'name'],
                'unique_together': {('level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('file', models.FileField(help_text='Uploaded to Cloudflare R2 in production via django-storages.', upload_to='resources/%Y/%m/')),
                ('is_free', models.BooleanField(db_index=True, default=True, help_text='Free resources are downloadable without payment.')),
                ('price', models.DecimalField(decimal_places=2, default='0.00', help_text='Purchase price in KES. Ignored when is_free=True.', max_digits=10)),
                ('downloads', models.PositiveIntegerField(default=0, help_text='Cumulative download count. Increment via F() expression.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.grade')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resources.learningarea')),
                ('vendor', models.ForeignKey(blank=True, help_text='The content creator / vendor who owns this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Item',
                'verbose_name_plural': 'Resource Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['grade', 'learning_area'], name='resources_r_grade_i_12c7ff_idx'), models.Index(fields=['is_free', '-created_at'], name='resources_r_is_free_82e8ab_idx')],
            },
        ),
    ]
