# Generated by Django 6.0.3 on 2026-04-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('lesson_plan', 'Lesson Plan'), ('schemes_of_work', 'Schemes of Work'), ('curriculum_design', 'Curriculum Design'), ('record_of_work', 'Record of Work'), ('teachers_guide', 'Teachers Guide'), ('textbook', 'Textbook'), ('notes', 'Notes'), ('exam', 'Exam'), ('other', 'Other'), ('report_card', 'Report Card')], default='other', help_text='The type of resource.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='downloads',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative download count.'),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='file',
            field=models.FileField(upload_to='resources/%Y/%m/'),
        ),
    ]
