# Generated by Django 6.0.3 on 2026-04-05 08:54

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourceitem_resource_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
