# Generated by Django 6.0.4 on 2026-04-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resourceitem_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('lesson_plan', 'Lesson Plan'), ('schemes_of_work', 'Schemes of Work'), ('curriculum_design', 'Curriculum Design'), ('record_of_work', 'Record of Work'), ('teachers_guide', 'Teachers Guide'), ('textbook', 'Textbook'), ('notes', 'Notes'), ('exam', 'Exam'), ('other', 'Other'), ('report_card', 'Report Card'), ('holiday_assignment', 'Holiday Assignment')], default='other', help_text='The type of resource.', max_length=50, null=True),
        ),
    ]
