# Generated by Django 6.0.4 on 2026-04-14 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_resourceitem_resource_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resourceitem',
            index=models.Index(fields=['-updated_at'], name='resources_r_updated_6b95ec_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceitem',
            index=models.Index(fields=['-resource_type'], name='resources_r_resourc_23b55b_idx'),
        ),
    ]
