# Generated by Django 6.0.4 on 2026-04-16 09:26

import django.db.models.functions.text
import django.utils.timezone
from django.utils.text import slugify

import validators.presets
import seo.models
from django.db import migrations, models


def _generate_unique_slugs(apps, schema_editor):
    """
    Generate unique slugs for Grade model .
    """

    Grade = apps.get_model('resources', 'Grade')

    grades = Grade.objects.filter(slug='')

    if grades.exists():

        for grade in grades:
            grade.slug = slugify(grade.name)

        Grade.objects.bulk_update(grades, ['slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0007_resourceitem_resources_r_updated_6b95ec_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ['order', 'slug'], 'verbose_name': 'Education Level',
                     'verbose_name_plural': 'Education Levels'},
        ),
        migrations.AlterModelOptions(
            name='learningarea',
            options={'ordering': ['slug'], 'verbose_name': 'Learning Area', 'verbose_name_plural': 'Learning Areas'},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for this page', null=True,
                                    storage=seo.models.PublicFilesStorageCallable(), upload_to='featured_images/%Y/%m/',
                                    validators=[validators.presets.validate_image_file]),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='meta_description',
            field=models.CharField(blank=True,
                                   help_text='SEO description (160 chars max). Leave blank to auto-generate.',
                                   max_length=160),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (60 chars max). Leave blank to auto-generate.',
                                   max_length=60),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for this page', null=True,
                                    storage=seo.models.PublicFilesStorageCallable(), upload_to='featured_images/%Y/%m/',
                                    validators=[validators.presets.validate_image_file]),
        ),
        migrations.AddField(
            model_name='grade',
            name='meta_description',
            field=models.CharField(blank=True,
                                   help_text='SEO description (160 chars max). Leave blank to auto-generate.',
                                   max_length=160),
        ),
        migrations.AddField(
            model_name='grade',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='grade',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (60 chars max). Leave blank to auto-generate.',
                                   max_length=60),
        ),
        migrations.AddField(
            model_name='grade',
            name='slug',
            field=models.SlugField(max_length=60, blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='learningarea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningarea',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for this page', null=True,
                                    storage=seo.models.PublicFilesStorageCallable(), upload_to='featured_images/%Y/%m/',
                                    validators=[validators.presets.validate_image_file]),
        ),
        migrations.AddField(
            model_name='learningarea',
            name='meta_description',
            field=models.CharField(blank=True,
                                   help_text='SEO description (160 chars max). Leave blank to auto-generate.',
                                   max_length=160),
        ),
        migrations.AddField(
            model_name='learningarea',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='learningarea',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (60 chars max). Leave blank to auto-generate.',
                                   max_length=60),
        ),
        migrations.AddField(
            model_name='learningarea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='slug',
            field=models.SlugField(max_length=110, unique=True),
        ),
        migrations.AlterField(
            model_name='learningarea',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='learningarea',
            name='slug',
            field=models.SlugField(max_length=110, unique=True),
        ),
        migrations.AlterField(
            model_name='resourceitem',
            name='slug',
            field=models.SlugField(max_length=265, unique=True),
        ),
        migrations.AddConstraint(
            model_name='educationlevel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'),
                                               name='unique_education_level_name',
                                               violation_error_message='Education level name must be unique'),
        ),

        migrations.RunPython(_generate_unique_slugs),
    ]
