# Generated by Django 6.0.4 on 2026-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_educationlevel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('level', 'slug')},
        ),
    ]
