# Generated by Django 6.0.4 on 2026-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_grade_slug_alter_grade_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='file',
            field=models.FileField(max_length=255, upload_to='resources/%Y/%m/'),
        ),
    ]
