# Generated by Django 6.0.4 on 2026-04-16 20:11

import resources.models
import resources.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_alter_resourceitem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='file',
            field=models.FileField(max_length=300, storage=resources.models.ResourcesPublicFilesStorageCallable(), upload_to=resources.utils.file_upload_path),
        ),
    ]
