# Generated by Django 6.0.4 on 2026-04-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_alter_resourceitem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationlevel',
            name='focus_keyword',
            field=models.CharField(blank=True, default='', help_text='Enter the main keyword this page should rank for.', max_length=60),
        ),
        migrations.AddField(
            model_name='grade',
            name='focus_keyword',
            field=models.CharField(blank=True, default='', help_text='Enter the main keyword this page should rank for.', max_length=60),
        ),
        migrations.AddField(
            model_name='learningarea',
            name='focus_keyword',
            field=models.CharField(blank=True, default='', help_text='Enter the main keyword this page should rank for.', max_length=60),
        ),
        migrations.AddField(
            model_name='resourceitem',
            name='focus_keyword',
            field=models.CharField(blank=True, default='', help_text='Enter the main keyword this page should rank for.', max_length=60),
        ),
    ]
