# Generated by Django 6.0.4 on 2026-04-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_academicsession_slug'),
        ('resources', '0012_educationlevel_focus_keyword_grade_focus_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceitem',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='core.academicsession'),
        ),
    ]
