# Generated by Django 6.0.4 on 2026-05-01 06:47

import resources.models
import resources.utils
import validators.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_resourceitem_academic_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='file',
            field=models.FileField(max_length=300, storage=resources.models.ResourcesPublicFilesStorageCallable(), upload_to=resources.utils.file_upload_path, validators=[validators.core.DeepSignatureValidator(allowed_mimetypes=['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.oasis.opendocument.presentation', 'application/msword', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/rtf', 'application/epub+zip']), validators.core.DeepSignatureValidator(allowed_mimetypes=['video/mp4', 'video/quicktime', 'video/webm', 'video/ogg', 'video/x-msvideo', 'video/x-matroska', 'video/x-flv']), validators.core.DeepSignatureValidator(allowed_mimetypes=['application/zip', 'application/x-7z-compressed', 'application/x-rar-compressed', 'application/x-tar', 'application/gzip', 'application/x-bzip2', 'application/x-xz', 'application/zstd', 'application/x-lz4']), validators.core.DeepSignatureValidator(allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp', 'image/tiff', 'image/avif', 'image/heic', 'image/svg+xml', 'image/x-icon'])]),
        ),
    ]
