# Generated by Django 6.0.4 on 2026-05-01 07:05

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_alter_resourceitem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
