# Generated by Django 6.0.4 on 2026-05-01 07:19

import resources.models
import resources.utils
import validators.core
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_alter_resourceitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='file',
            field=models.FileField(max_length=300, storage=resources.models.ResourcesPublicFilesStorageCallable(), upload_to=resources.utils.file_upload_path, validators=[validators.core.DeepSignatureValidator(allowed_mimetypes={'application/epub+zip', 'application/msword', 'application/rtf', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.oasis.opendocument.presentation', 'application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.oasis.opendocument.text', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'})]),
        ),
    ]
