# Generated by Django 6.0.5 on 2026-05-09 10:36

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0019_alter_resourceitem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceitem',
            name='description',
            field=core.fields.SafeHTMLField(blank=True, default=''),
        ),
    ]
