# Generated by Django 6.0.5 on 2026-05-15 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_alter_resourceitem_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', help_text='Not displayed publicly.', max_length=254)),
                ('body', models.TextField(max_length=2000)),
                ('is_approved', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='resources.resourcecomment')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resources.resourceitem')),
                ('user', models.ForeignKey(blank=True, help_text='Set when the commenter is logged in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Comment',
                'verbose_name_plural': 'Resource Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
