name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: ${{ vars.PYTHON_VERSION || '3.12' }}
  IMAGE_NAME: docker.io/paulmbui/cbe_resource_hub

jobs:
  ####################################
  #           TESTS JOB
  ####################################
  tests:
    name: Run Django Tests in Parallel
    uses: ./.github/workflows/_test.yml
    with:
      python-version: ${{ vars.PYTHON_VERSION || '3.12' }}

  ####################################
  #      BUILD & PUSH JOB
  ####################################
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest
    needs: [ tests ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build & Push image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:edge
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Image digest
        run: echo "Image pushed with digest ${{ steps.docker_build.outputs.digest }}"
